-- Create dental_clinics table
CREATE TABLE public.dental_clinics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NULL,
  region varchar NULL,
  address varchar NULL,  
  phone varchar NULL,
  description varchar NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.dental_clinics ENABLE ROW LEVEL SECURITY;

-- Create policies for dental_clinics
CREATE POLICY "Public can view dental_clinics" 
ON public.dental_clinics 
FOR SELECT 
USING (true);

CREATE POLICY "Admins can manage dental_clinics" 
ON public.dental_clinics 
FOR ALL 
USING (is_admin());

-- Create radiology_centers table
CREATE TABLE public.radiology_centers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NULL,
  region varchar NULL,
  address varchar NULL,
  phone varchar NULL,
  description varchar NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.radiology_centers ENABLE ROW LEVEL SECURITY;

-- Create policies for radiology_centers
CREATE POLICY "Public can view radiology_centers" 
ON public.radiology_centers 
FOR SELECT 
USING (true);

CREATE POLICY "Admins can manage radiology_centers" 
ON public.radiology_centers 
FOR ALL 
USING (is_admin());

-- Create optical_clinics table
CREATE TABLE public.optical_clinics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NULL,
  region varchar NULL,
  address varchar NULL,
  phone varchar NULL,
  description varchar NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.optical_clinics ENABLE ROW LEVEL SECURITY;

-- Create policies for optical_clinics
CREATE POLICY "Public can view optical_clinics" 
ON public.optical_clinics 
FOR SELECT 
USING (true);

CREATE POLICY "Admins can manage optical_clinics" 
ON public.optical_clinics 
FOR ALL 
USING (is_admin());

-- Create physical_therapy_centers table
CREATE TABLE public.physical_therapy_centers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NULL,
  region varchar NULL,
  address varchar NULL,
  phone varchar NULL,
  description varchar NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.physical_therapy_centers ENABLE ROW LEVEL SECURITY;

-- Create policies for physical_therapy_centers
CREATE POLICY "Public can view physical_therapy_centers" 
ON public.physical_therapy_centers 
FOR SELECT 
USING (true);

CREATE POLICY "Admins can manage physical_therapy_centers" 
ON public.physical_therapy_centers 
FOR ALL 
USING (is_admin());